### ISSUE TITLE
Failed to close oonib report.

### ISSUE THREAD

**Issue by andresazp** [TheTorProject/ooni-probe#435]
Frequently I'm getting
[!] Failed to close oonib report.
On base httprequest tests

I haven't been able to isolate it further (not a whole lot of time at the moment), but I'll post here when we know more while also hoping that this rings a bell with someone else

**Comment by andresazp** [comment]
Some context:
```
[!] Error in writing report entry
[D] Task <ooni.tasks.ReportEntry object at 0xd4b4f0> has failed 4 times
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 434, in errback
    self._startRunCallbacks(fail)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 501, in _startRunCallbacks
    self._runCallbacks()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1184, in gotResult
    _inlineCallbacks(r, g, deferred)
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python2.7/dist-packages/ooniprobe-1.3.2-py2.7.egg/ooni/reporter.py", line 277, in writeReportEntry
    raise errors.OONIBReportUpdateError
ooni.errors.OONIBReportUpdateError: 
[D] Permanent failure for <ooni.tasks.ReportEntry object at 0xd4b4f0>
[D] Checking all tasks for completion 759 == 760
[D] Checking all tasks for completion 760 == 760
Report ID: gW68V8AAXvLTiWOzhQ2JjYBvmBAzU1lTQvk6lzoLRXsq0CTWsAWHqTVDoCaDb96Z
[D] Closing the report http://tggp6jv5aaul54kk.onion/report/2015-11-29T033225Z_AS8048_1hqs8XqmfWprgaJhh7EiVwVYVsZiIaD0sRRvvSGK33rFmWgwIX/close
Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 317, in addCallback
    callbackKeywords=kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 306, in addCallbacks
    self._runCallbacks()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/ooniprobe-1.3.2-py2.7.egg/ooni/reporter.py", line 447, in execute
    d = defer.maybeDeferred(f, *arg, **kw)
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/ooniprobe-1.3.2-py2.7.egg/ooni/reporter.py", line 514, in _incomplete
    raise errors.ReportNotCreated()
ooni.errors.ReportNotCreated: 

[!] Failed to close oonib report.
```

**Comment by hellais** [comment]
Is this using our collector or your own one? If the later could you perhaps also get some debug logs from your collector?

Also does the report file end up being created?

**Comment by hellais** [comment]
I am going to close this issue as it's related to a pretty old version of ooniprobe and there is no enough information to be able to reproduce and confirm if it's still present in the current version.

If the problem persists please re-open another issue.

Thanks!
