### ISSUE TITLE
Could not run dns_spoof and other scapy based tests

### ISSUE THREAD

**Issue by bassosimone** [TheTorProject/ooni-probe#472]
Inside a Vagrant obtained with `vagrant up` run in the root directory of the repository, I run the following command:

```bash
sudo ./bin/ooniprobe -vc httpo://$onion_address manipulation/dns_spoof \
    -r 8.8.8.1:53 -b 8.8.8.8:53 -h www.kernel.org
```

and the test fails with this error: `exceptions.OSError: couldn't enable immediate mode`.

I have experienced failures also for other scapy based tests. This occurred while I was evaluating pull request #456 (but I have just repeated the test at a0fc5e6f4ef76 with equal error).

Full log follows:
```
/usr/local/lib/python2.7/dist-packages/zope.interface-4.1.3-py2.7-linux-i686.egg/zope/__init__.py:3: UserWarning: Module twisted was already imported from /usr/local/lib/python2.7/dist-packages/Twisted-16.1.0-py2.7-linux-i686.egg/twisted/__init__.pyc, but /usr/local/lib/python2.7/dist-packages/txtorcon-0.14.2-py2.7.egg is being added to sys.path
  import pkg_resources
WARNING: running ooniprobe involves some risk that varies greatly
         from country to country. You should be aware of this when
         running the tool. Read more about this in the manpage or README.
Log opened.
[D] No test deck detected
[D] Checking if hostname is present
[D] Checking if resolver is present
Starting Tor...
[D] Setting control port as 37960
[D] Setting SOCKS port as 58517
Spawning tor process with DataDirectory /tmp/tortmpJxXDZy
5%: Connecting to directory server
10%: Finishing handshake with directory server
15%: Establishing an encrypted directory connection
20%: Asking for networkstatus consensus
25%: Loading networkstatus consensus
40%: Loading authority key certs
45%: Asking for relay descriptors
50%: Loading relay descriptors
51%: Loading relay descriptors
52%: Loading relay descriptors
53%: Loading relay descriptors
55%: Loading relay descriptors
58%: Loading relay descriptors
62%: Loading relay descriptors
68%: Loading relay descriptors
73%: Loading relay descriptors
80%: Connecting to the Tor network
90%: Establishing a Tor circuit
100%: Done
[D] Building a TorState
Successfully bootstrapped Tor
[D] We now have the following circuits: 
[snip]
Fetching required net test inputs...
[D] Fetching and verifying inputs
Looking up collector and test helpers
Reporting [snip]
[D] Sending [snip]
Creating report with OONIB Reporter. Please be patient.
This may take up to 1-2 minutes...
[D] Creating /ooni/report-dns_spoof-2016-04-04T152103Z.yamloo
[D] Writing report with YAML reporter
[!] Host is not reachable (HostUnreachable error
[D] Starting this task <generator object generateMeasurements at 0xa37f25c>
[D] Running <class 'ooni.nettests.manipulation.dns_spoof.DNSSpoof'> test_a_lookup
[D] Scapy factory not set, registering it.
[!] Could not start the director
[!] An unhandled exception occurred while starting the director!
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Twisted-16.1.0-py2.7-linux-i686.egg/twisted/internet/defer.py", line 434, in errback
    self._startRunCallbacks(fail)
  File "/usr/local/lib/python2.7/dist-packages/Twisted-16.1.0-py2.7-linux-i686.egg/twisted/internet/defer.py", line 501, in _startRunCallbacks
    self._runCallbacks()
  File "/usr/local/lib/python2.7/dist-packages/Twisted-16.1.0-py2.7-linux-i686.egg/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/Twisted-16.1.0-py2.7-linux-i686.egg/twisted/internet/defer.py", line 1184, in gotResult
    _inlineCallbacks(r, g, deferred)
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/Twisted-16.1.0-py2.7-linux-i686.egg/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python2.7/dist-packages/Twisted-16.1.0-py2.7-linux-i686.egg/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python2.7/dist-packages/ooniprobe-1.3.2-py2.7.egg/ooni/oonicli.py", line 321, in post_director_start
    global_options['no-yamloo'])
  File "/usr/local/lib/python2.7/dist-packages/Twisted-16.1.0-py2.7-linux-i686.egg/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python2.7/dist-packages/ooniprobe-1.3.2-py2.7.egg/ooni/director.py", line 266, in startNetTest
    self.measurementManager.schedule(net_test.generateMeasurements())
  File "/usr/local/lib/python2.7/dist-packages/ooniprobe-1.3.2-py2.7.egg/ooni/managers.py", line 115, in schedule
    self._fillSlots()
  File "/usr/local/lib/python2.7/dist-packages/ooniprobe-1.3.2-py2.7.egg/ooni/managers.py", line 60, in _fillSlots
    task = self._tasks.next()
  File "/usr/local/lib/python2.7/dist-packages/ooniprobe-1.3.2-py2.7.egg/ooni/nettest.py", line 537, in generateMeasurements
    input)
  File "/usr/local/lib/python2.7/dist-packages/ooniprobe-1.3.2-py2.7.egg/ooni/nettest.py", line 501, in makeMeasurement
    measurement = Measurement(test_instance, test_method, test_input)
  File "/usr/local/lib/python2.7/dist-packages/ooniprobe-1.3.2-py2.7.egg/ooni/tasks.py", line 113, in __init__
    self.testInstance._setUp()
  File "/usr/local/lib/python2.7/dist-packages/ooniprobe-1.3.2-py2.7.egg/ooni/templates/scapyt.py", line 50, in _setUp
    config.scapyFactory = ScapyFactory(config.advanced.interface)
  File "/usr/local/lib/python2.7/dist-packages/ooniprobe-1.3.2-py2.7.egg/ooni/utils/txscapy.py", line 97, in __init__
    super_socket = conf.L3socket(iface=interface)
  File "/usr/local/lib/python2.7/dist-packages/scapy_real-2.2.0_dev-py2.7.egg/scapy/arch/pcapdnet.py", line 202, in __init__
    self.ins = open_pcap(iface, 1600, 0, 100)
  File "/usr/local/lib/python2.7/dist-packages/scapy_real-2.2.0_dev-py2.7.egg/scapy/arch/pcapdnet.py", line 53, in <lambda>
    open_pcap = lambda *args,**kargs: _PcapWrapper_pypcap(*args,**kargs)
  File "/usr/local/lib/python2.7/dist-packages/scapy_real-2.2.0_dev-py2.7.egg/scapy/arch/pcapdnet.py", line 47, in __init__
    self.pcap = pcap.pcap(device, snaplen, promisc, immediate=1, timeout_ms=to_ms)
  File "pcap.pyx", line 210, in pcap.pcap.__init__ (pcap.c:1773)
    
exceptions.OSError: couldn't enable immediate mode
Main loop terminated.
```

**Comment by anadahz** [comment]
I have the same issue while running ooni-probe in docker.
i think this has been in introduced in pypcap version 1.1.4
Downgrading pypcap (`pip install 'pypcap<1.1.4'`) seems to eliminate this issue.
@bassosimone can you confirm?

**Comment by anadahz** [comment]
Possible related bug: https://github.com/pynetwork/pypcap/issues/12

**Comment by anadahz** [comment]
Reference: as @bassosimone mentioned the pypcap version 1.4 [changes](https://github.com/pynetwork/pypcap/compare/v1.1.3...v1.1.4?w=1)

**Comment by hellais** [comment]
Pypcap 1.1.5 is now released so this bug is fixed. https://pypi.python.org/pypi/pypcap/1.1.5

**Comment by anadahz** [comment]
Not sure if this is the best place to report it but I think it's related. 
While running the ooniprobe fast deck I encounter this error:
```
Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python2.7/dist-packages/ooniprobe-1.4.1-py2.7.egg/ooni/nettests/manipulation/traceroute.py", line 62, in run_traceroute
    yield traceroute(self.localOptions['backend'])
  File "/usr/local/lib/python2.7/dist-packages/ooniprobe-1.4.1-py2.7.egg/ooni/utils/txscapy.py", line 380, in TCPTraceroute
    seq=RandShort()))
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1274, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python2.7/dist-packages/ooniprobe-1.4.1-py2.7.egg/ooni/utils/txscapy.py", line 396, in sendPackets
    self.factory.super_socket.send(packet)
  File "/usr/local/lib/python2.7/dist-packages/scapy/arch/pcapdnet.py", line 244, in send
    sx = str(cls()/x)
  File "/usr/local/lib/python2.7/dist-packages/scapy/packet.py", line 263, in __str__
    return self.build()
  File "/usr/local/lib/python2.7/dist-packages/scapy/packet.py", line 321, in build
    p = self.do_build()
  File "/usr/local/lib/python2.7/dist-packages/scapy/packet.py", line 310, in do_build
    pkt = self.self_build()
  File "/usr/local/lib/python2.7/dist-packages/scapy/packet.py", line 301, in self_build
    p = f.addfield(self, p, val)
  File "/usr/local/lib/python2.7/dist-packages/scapy/fields.py", line 70, in addfield
    return s+struct.pack(self.fmt, self.i2m(pkt,val))
  File "/usr/local/lib/python2.7/dist-packages/scapy/layers/l2.py", line 94, in i2m
    return MACField.i2m(self, pkt, self.i2h(pkt, x))
  File "/usr/local/lib/python2.7/dist-packages/scapy/layers/l2.py", line 88, in i2h
    x = conf.neighbor.resolve(pkt,pkt.payload)
  File "/usr/local/lib/python2.7/dist-packages/scapy/layers/l2.py", line 38, in resolve
    return self.resolvers[k](l2inst,l3inst)
  File "/usr/local/lib/python2.7/dist-packages/scapy/layers/inet.py", line 727, in <lambda>
    conf.neighbor.register_l3(Ether, IP, lambda l2,l3: getmacbyip(l3.dst))
  File "/usr/local/lib/python2.7/dist-packages/scapy/layers/l2.py", line 72, in getmacbyip
    nofilter=1)
  File "/usr/local/lib/python2.7/dist-packages/scapy/sendrecv.py", line 375, in srp1
    a,b=srp(*args,**kargs)
  File "/usr/local/lib/python2.7/dist-packages/scapy/sendrecv.py", line 358, in srp
    a,b=sndrcv(s ,x,*args,**kargs)
  File "/usr/local/lib/python2.7/dist-packages/scapy/sendrecv.py", line 129, in sndrcv
    inp, out, err = select(inmask,[],[], remaintime)
select.error: (4, 'Interrupted system call')
```

**Comment by bassosimone** [comment]
In general `EINTR` is delivered when a child process dies and, in doing that, it interrupts a slow system call (e.g., select or a blocking send or recv). Are there any processes that could die in our case?

Is pypcap related in any way to scapy? Asking because this seems a scapy problem. (If really the problem is unrelated to pypcap, perhaps we should create a separate issue.)

Searching on Google I also found [this bug that describes our problem](https://bitbucket.org/secdev/scapy/issues/473/scapy-sendrecv-selects-eintr-problem-in). AFAIK the proposed patch (i.e. restarting select if it receives SIGCHLD) is the correct way of dealing with SIGCHLD (it is correct as in portable, because there are kernels where SIGCHLD is ignored, so restarting the syscall makes behavior uniform).

**Comment by hellais** [comment]
Yes I looked into this a bit and it seems like the problem has to do with scapy. The patch proposed in the linked ticket does seem to work as expected and I submitted a PR with the patch to scapy: https://github.com/secdev/scapy/pull/138

**Comment by hellais** [comment]
FYI scapy has merged this patch into their master branch.

**Comment by anadahz** [comment]
I confirm the latest patch fixes this bug.
Until the newest release:
`# pip install --upgrade git+https://github.com/secdev/scapy.git#scapy-real`
