### ISSUE TITLE
Stalling ooniprobe measurements

### ISSUE THREAD

**Issue by hellais** [TheTorProject/ooni-probe#491]
While developing on the web_connectivity branch I have run into an issue where the test will stall and this traceback is printed out.

I am still unsure if it's a bug specific to that branch or if it's actually present in ooniprobe itself.

I haven't seen this bug appear in a very long time and I believe in the past with @aagbsn we had done quite a bit of work to track it down and fix it.

I am taking not of it here though as a reminder that I should investigate this further.

```
Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
  File "/ooni-probe/ooni/managers.py", line 61, in _fillSlots
    self._run(task)
  File "/ooni-probe/ooni/managers.py", line 79, in _run
    d.addErrback(self._failed, task)
  File "/ooni-probe/lib/python2.7/site-packages/twisted/internet/defer.py", line 328, in addErrback
    errbackKeywords=kw)
  File "/ooni-probe/lib/python2.7/site-packages/twisted/internet/defer.py", line 306, in addCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "ooni-probe/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/ooni-probe/ooni/managers.py", line 162, in _failed
    super(LinkedTaskManager, self)._failed(result, task)
  File "/ooni-probe/ooni/managers.py", line 37, in _failed
    self._active_tasks.remove(task)
exceptions.ValueError: list.remove(x): x not in list
```

**Comment by hellais** [comment]
I haven't seen this anymore and doing testing for it has not highlighted the problem anymore. I suspect it was only happening due to changes made in an old web_connectivity branch.

Closing as invalid.
