### ISSUE TITLE
Increase timeout for vanilla_tor test

### ISSUE THREAD

**Issue by anadahz** [TheTorProject/ooni-probe#508]
ooniprobe version: 1.4.2
branch: feature/testing-deck

Made a testing test deck, after some runs I realized:
- PCAP collection shouldn't happen
- Traceroute test throught out a bunch of errors
- Vanilla tor test timeout should be increased

`ooniprobe -n -i data/decks/all_tests.deck`

```
Fetching required net test inputs...
Looking up collector and test helpers
Setting collector and test helpers for
captiveportal
Setting collector and test helpers for http_host
Setting collector and test helpers for dns_spoof
Setting collector and test helpers for traceroute
Setting collector and test helpers for
http_invalid_request_line
Setting collector and test helpers for
http_header_field_manipulation
Setting collector and test helpers for
meek_fronted_requests_test
Setting collector and test helpers for vanilla_tor
Setting collector and test helpers for tcp_connect
Setting collector and test helpers for
dns_consistency
Setting collector and test helpers for
bridge_reachility
Setting collector and test helpers for
http_url_list
Starting packet capture to:
report-captiveportal-2016-05-19T000528Z.pcap
```

```
Starting packet capture to: report-traceroute-2016-05-19T000817Z.pcap
Running TCP traceroute towards 213.138.109.232
This will take out 57.2 seconds
Unhandled error in Deferred:
Unhandled Error
        Traceback (most recent call last):
          File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
            result = g.send(result)
          File "/usr/local/lib/python2.7/dist-packages/ooniprobe-1.4.2-py2.7.egg/ooni/nettests/manipulation/traceroute.py", line 62, in run_traceroute
            yield traceroute(self.localOptions['backend'])
          File "/usr/local/lib/python2.7/dist-packages/ooniprobe-1.4.2-py2.7.egg/ooni/utils/txscapy.py", line 380, in TCPTraceroute
            seq=RandShort()))
          File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1274, in unwindGenerator
            return _inlineCallbacks(None, gen, Deferred())
        --- <exception caught here> ---
          File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
            result = g.send(result)
          File "/usr/local/lib/python2.7/dist-packages/ooniprobe-1.4.2-py2.7.egg/ooni/utils/txscapy.py", line 396, in sendPackets
            self.factory.super_socket.send(packet)
          File "/usr/local/lib/python2.7/dist-packages/scapy_real-2.2.0.dev0-py2.7.egg/scapy/arch/pcapdnet.py", line 244, in send
            sx = str(cls()/x)
          File "/usr/local/lib/python2.7/dist-packages/scapy_real-2.2.0.dev0-py2.7.egg/scapy/packet.py", line 263, in __str__
            return self.build()
          File "/usr/local/lib/python2.7/dist-packages/scapy_real-2.2.0.dev0-py2.7.egg/scapy/packet.py", line 321, in build
            p = self.do_build()
          File "/usr/local/lib/python2.7/dist-packages/scapy_real-2.2.0.dev0-py2.7.egg/scapy/packet.py", line 310, in do_build
            pkt = self.self_build()
          File "/usr/local/lib/python2.7/dist-packages/scapy_real-2.2.0.dev0-py2.7.egg/scapy/packet.py", line 301, in self_build
            p = f.addfield(self, p, val)
          File "/usr/local/lib/python2.7/dist-packages/scapy_real-2.2.0.dev0-py2.7.egg/scapy/fields.py", line 70, in addfield
            return s+struct.pack(self.fmt, self.i2m(pkt,val))
          File "/usr/local/lib/python2.7/dist-packages/scapy_real-2.2.0.dev0-py2.7.egg/scapy/layers/l2.py", line 94, in i2m
            return MACField.i2m(self, pkt, self.i2h(pkt, x))
          File "/usr/local/lib/python2.7/dist-packages/scapy_real-2.2.0.dev0-py2.7.egg/scapy/layers/l2.py", line 88, in i2h
            x = conf.neighbor.resolve(pkt,pkt.payload)
          File "/usr/local/lib/python2.7/dist-packages/scapy_real-2.2.0.dev0-py2.7.egg/scapy/layers/l2.py", line 38, in resolve
            return self.resolvers[k](l2inst,l3inst)
          File "/usr/local/lib/python2.7/dist-packages/scapy_real-2.2.0.dev0-py2.7.egg/scapy/layers/inet.py", line 727, in <lambda>
            conf.neighbor.register_l3(Ether, IP, lambda l2,l3: getmacbyip(l3.dst))
          File "/usr/local/lib/python2.7/dist-packages/scapy_real-2.2.0.dev0-py2.7.egg/scapy/layers/l
2.py", line 72, in getmacbyip
            nofilter=1)
          File "/usr/local/lib/python2.7/dist-packages/scapy_real-2.2.0.dev0-py2.7.egg/scapy/sendrecv.py", line 375, in srp1
            a,b=srp(*args,**kargs)
          File "/usr/local/lib/python2.7/dist-packages/scapy_real-2.2.0.dev0-py2.7.egg/scapy/sendrecv.py", line 358, in srp
            a,b=sndrcv(s ,x,*args,**kargs)
          File "/usr/local/lib/python2.7/dist-packages/scapy_real-2.2.0.dev0-py2.7.egg/scapy/sendrecv.py", line 129, in sndrcv
            inp, out, err = select(inmask,[],[], remaintime)
        select.error: (4, 'Interrupted system call')
        
Unhandled error in Deferred:
Unhandled Error
        Traceback (most recent call last):
          File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
            result = g.send(result)
          File "/usr/local/lib/python2.7/dist-packages/ooniprobe-1.4.2-py2.7.egg/ooni/nettests/manipulation/traceroute.py", line 62, in run_traceroute
            yield traceroute(self.localOptions['backend'])
          File "/usr/local/lib/python2.7/dist-packages/ooniprobe-1.4.2-py2.7.egg/ooni/utils/txscapy.py", line 380, in TCPTraceroute
            seq=RandShort()))
          File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1274, in unwindGenerator
            return _inlineCallbacks(None, gen, Deferred())
        --- <exception caught here> ---
          File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
            result = g.send(result)
          File "/usr/local/lib/python2.7/dist-packages/ooniprobe-1.4.2-py2.7.egg/ooni/utils/txscapy.py", line 396, in sendPackets
            self.factory.super_socket.send(packet)
          File "/usr/local/lib/python2.7/dist-packages/scapy_real-2.2.0.dev0-py2.7.egg/scapy/arch/pcapdnet.py", line 244, in send
            sx = str(cls()/x)
          File "/usr/local/lib/python2.7/dist-packages/scapy_real-2.2.0.dev0-py2.7.egg/scapy/packet.py", line 263, in __str__
            return self.build()
          File "/usr/local/lib/python2.7/dist-packages/scapy_real-2.2.0.dev0-py2.7.egg/scapy/packet.py", line 321, in build
            p = self.do_build()
          File "/usr/local/lib/python2.7/dist-packages/scapy_real-2.2.0.dev0-py2.7.egg/scapy/packet.py", line 310, in do_build
            pkt = self.self_build()
          File "/usr/local/lib/python2.7/dist-packages/scapy_real-2.2.0.dev0-py2.7.egg/scapy/packet.py", line 301, in self_build
            p = f.addfield(self, p, val)
          File "/usr/local/lib/python2.7/dist-packages/scapy_real-2.2.0.dev0-py2.7.egg/scapy/fields.py", line 70, in addfield
            return s+struct.pack(self.fmt, self.i2m(pkt,val))
          File "/usr/local/lib/python2.7/dist-packages/scapy_real-2.2.0.dev0-py2.7.egg/scapy/layers/l2.py", line 94, in i2m
            return MACField.i2m(self, pkt, self.i2h(pkt, x))
          File "/usr/local/lib/python2.7/dist-packages/scapy_real-2.2.0.dev0-py2.7.egg/scapy/layers/l2.py", line 88, in i2h
            x = conf.neighbor.resolve(pkt,pkt.payload)
          File "/usr/local/lib/python2.7/dist-packages/scapy_real-2.2.0.dev0-py2.7.egg/scapy/layers/l2.py", line 38, in resolve
            return self.resolvers[k](l2inst,l3inst)
          File "/usr/local/lib/python2.7/dist-packages/scapy_real-2.2.0.dev0-py2.7.egg/scapy/layers/inet.py", line 727, in <lambda>
            conf.neighbor.register_l3(Ether, IP, lambda l2,l3: getmacbyip(l3.dst))
          File "/usr/local/lib/python2.7/dist-packages/scapy_real-2.2.0.dev0-py2.7.egg/scapy/layers/l2.py", line 72, in getmacbyip
            nofilter=1)
          File "/usr/local/lib/python2.7/dist-packages/scapy_real-2.2.0.dev0-py2.7.egg/scapy/sendrecv.py", line 375, in srp1
            a,b=srp(*args,**kargs)
          File "/usr/local/lib/python2.7/dist-packages/scapy_real-2.2.0.dev0-py2.7.egg/scapy/sendrecv.py", line 358, in srp
            a,b=sndrcv(s ,x,*args,**kargs)
          File "/usr/local/lib/python2.7/dist-packages/scapy_real-2.2.0.dev0-py2.7.egg/scapy/sendrecv.py", line 129, in sndrcv
            inp, out, err = select(inmask,[],[], remaintime)
        select.error: (4, 'Interrupted system call')
        
Unhandled error in Deferred:
Unhandled Error
        Traceback (most recent call last):
          File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
            result = g.send(result)
          File "/usr/local/lib/python2.7/dist-packages/ooniprobe-1.4.2-py2.7.egg/ooni/nettests/manipulation/traceroute.py", line 62, in run_traceroute
            yield traceroute(self.localOptions['backend'])
          File "/usr/local/lib/python2.7/dist-packages/ooniprobe-1.4.2-py2.7.egg/ooni/utils/txscapy.py", line 380, in TCPTraceroute
            seq=RandShort()))
          File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1274, in unwindGenerator
            return _inlineCallbacks(None, gen, Deferred())
        --- <exception caught here> ---
          File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
            result = g.send(result)
          File "/usr/local/lib/python2.7/dist-packages/ooniprobe-1.4.2-py2.7.egg/ooni/utils/txscapy.py", line 396, in sendPackets
            self.factory.super_socket.send(packet)
          File "/usr/local/lib/python2.7/dist-packages/scapy_real-2.2.0.dev0-py2.7.egg/scapy/arch/pcapdnet.py", line 244, in send
            sx = str(cls()/x)
          File "/usr/local/lib/python2.7/dist-packages/scapy_real-2.2.0.dev0-py2.7.egg/scapy/packet.py", line 263, in __str__
            return self.build()
          File "/usr/local/lib/python2.7/dist-packages/scapy_real-2.2.0.dev0-py2.7.egg/scapy/packet.py", line 321, in build
            p = self.do_build()
          File "/usr/local/lib/python2.7/dist-packages/scapy_real-2.2.0.dev0-py2.7.egg/scapy/packet.py", line 310, in do_build
            pkt = self.self_build()
          File "/usr/local/lib/python2.7/dist-packages/scapy_real-2.2.0.dev0-py2.7.egg/scapy/packet.py", line 301, in self_build
            p = f.addfield(self, p, val)
          File "/usr/local/lib/python2.7/dist-packages/scapy_real-2.2.0.dev0-py2.7.egg/scapy/fields.py", line 70, in addfield
            return s+struct.pack(self.fmt, self.i2m(pkt,val))
          File "/usr/local/lib/python2.7/dist-packages/scapy_real-2.2.0.dev0-py2.7.egg/scapy/layers/l2.py", line 94, in i2m
            return MACField.i2m(self, pkt, self.i2h(pkt, x))
          File "/usr/local/lib/python2.7/dist-packages/scapy_real-2.2.0.dev0-py2.7.egg/scapy/layers/l2.py", line 88, in i2h
            x = conf.neighbor.resolve(pkt,pkt.payload)
          File "/usr/local/lib/python2.7/dist-packages/scapy_real-2.2.0.dev0-py2.7.egg/scapy/layers/l2.py", line 38, in resolve
            return self.resolvers[k](l2inst,l3inst)
          File "/usr/local/lib/python2.7/dist-packages/scapy_real-2.2.0.dev0-py2.7.egg/scapy/layers/inet.py", line 727, in <lambda>
            conf.neighbor.register_l3(Ether, IP, lambda l2,l3: getmacbyip(l3.dst))
          File "/usr/local/lib/python2.7/dist-packages/scapy_real-2.2.0.dev0-py2.7.egg/scapy/layers/l2.py", line 72, in getmacbyip
            nofilter=1)
          File "/usr/local/lib/python2.7/dist-packages/scapy_real-2.2.0.dev0-py2.7.egg/scapy/sendrecv.py", line 375, in srp1
            a,b=srp(*args,**kargs)
          File "/usr/local/lib/python2.7/dist-packages/scapy_real-2.2.0.dev0-py2.7.egg/scapy/sendrecv.py", line 358, in srp
            a,b=sndrcv(s ,x,*args,**kargs)
         File "/usr/local/lib/python2.7/dist-packages/scapy_real-2.2.0.dev0-py2.7.egg/scapy/sendrecv.py", line 129, in sndrcv
            inp, out, err = select(inmask,[],[], remaintime)
        select.error: (4, 'Interrupted system call')
        
Unhandled error in Deferred:
Unhandled Error
        Traceback (most recent call last):
          File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
            result = g.send(result)
          File "/usr/local/lib/python2.7/dist-packages/ooniprobe-1.4.2-py2.7.egg/ooni/nettests/manipulation/traceroute.py", line 62, in run_traceroute
            yield traceroute(self.localOptions['backend'])
          File "/usr/local/lib/python2.7/dist-packages/ooniprobe-1.4.2-py2.7.egg/ooni/utils/txscapy.py", line 380, in TCPTraceroute
            seq=RandShort()))
          File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1274, in unwindGenerator
            return _inlineCallbacks(None, gen, Deferred())
        --- <exception caught here> ---
          File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
            result = g.send(result)
          File "/usr/local/lib/python2.7/dist-packages/ooniprobe-1.4.2-py2.7.egg/ooni/utils/txscapy.py", line 396, in sendPackets
            self.factory.super_socket.send(packet)
          File "/usr/local/lib/python2.7/dist-packages/scapy_real-2.2.0.dev0-py2.7.egg/scapy/arch/pca
pdnet.py", line 244, in send
            sx = str(cls()/x)
          File "/usr/local/lib/python2.7/dist-packages/scapy_real-2.2.0.dev0-py2.7.egg/scapy/packet.py", line 263, in __str__
            return self.build()
          File "/usr/local/lib/python2.7/dist-packages/scapy_real-2.2.0.dev0-py2.7.egg/scapy/packet.py", line 321, in build
            p = self.do_build()
          File "/usr/local/lib/python2.7/dist-packages/scapy_real-2.2.0.dev0-py2.7.egg/scapy/packet.py", line 310, in do_build
            pkt = self.self_build()
          File "/usr/local/lib/python2.7/dist-packages/scapy_real-2.2.0.dev0-py2.7.egg/scapy/packet.py", line 301, in self_build
            p = f.addfield(self, p, val)
          File "/usr/local/lib/python2.7/dist-packages/scapy_real-2.2.0.dev0-py2.7.egg/scapy/fields.py", line 70, in addfield
            return s+struct.pack(self.fmt, self.i2m(pkt,val))
          File "/usr/local/lib/python2.7/dist-packages/scapy_real-2.2.0.dev0-py2.7.egg/scapy/layers/l2.py", line 94, in i2m
            return MACField.i2m(self, pkt, self.i2h(pkt, x))
          File "/usr/local/lib/python2.7/dist-packages/scapy_real-2.2.0.dev0-py2.7.egg/scapy/layers/l2.py", line 88, in i2h
            x = conf.neighbor.resolve(pkt,pkt.payload)
          File "/usr/local/lib/python2.7/dist-packages/scapy_real-2.2.0.dev0-py2.7.egg/scapy/layers/l2.py", line 38, in resolve
            return self.resolvers[k](l2inst,l3inst)
          File "/usr/local/lib/python2.7/dist-packages/scapy_real-2.2.0.dev0-py2.7.egg/scapy/layers/inet.py", line 727, in <lambda>
            conf.neighbor.register_l3(Ether, IP, lambda l2,l3: getmacbyip(l3.dst))
          File "/usr/local/lib/python2.7/dist-packages/scapy_real-2.2.0.dev0-py2.7.egg/scapy/layers/l2.py", line 72, in getmacbyip
            nofilter=1)
          File "/usr/local/lib/python2.7/dist-packages/scapy_real-2.2.0.dev0-py2.7.egg/scapy/sendrecv.py", line 375, in srp1
            a,b=srp(*args,**kargs)
          File "/usr/local/lib/python2.7/dist-packages/scapy_real-2.2.0.dev0-py2.7.egg/scapy/sendrecv.py", line 358, in srp
            a,b=sndrcv(s ,x,*args,**kargs)
          File "/usr/local/lib/python2.7/dist-packages/scapy_real-2.2.0.dev0-py2.7.egg/scapy/sendrecv.py", line 129, in sndrcv
            inp, out, err = select(inmask,[],[], remaintime)
        select.error: (4, 'Interrupted system call')
```
```
Starting packet capture to: report-vanilla_tor-2016-05-19T000923Z.pcap
Connecting to tor 0.2.7.6
2016-05-19 02:09:23+0200 [HTTP11ClientProtocol (TLSMemoryBIOProtocol),client] Spawning tor process wi
th DataDirectory /tmp/tmplgOvEM
Progress is at: 5%
Progress is at: 10%
Progress is at: 15%
Progress is at: 20%
Progress is at: 25%
Progress is at: 40%
Progress is at: 45%
Progress is at: 50%
Progress is at: 51%
Progress is at: 52%
Progress is at: 52%
Progress is at: 52%
Progress is at: 54%
Progress is at: 56%
Progress is at: 59%
Progress is at: 63%
Progress is at: 68%
Progress is at: 74%
Unhandled Error
        Traceback (most recent call last):
        Failure: exceptions.RuntimeError: Tor exited with error-code 0
Failed to connect to Tor
```

**Comment by hellais** [comment]
Regarding the error `        select.error: (4, 'Interrupted system call')`.

It was already reported in https://github.com/TheTorProject/ooni-probe/issues/472 and has been fixed in https://github.com/secdev/scapy/commit/78aff2eb73390c6b5cdabce5fcf44154e9cdbc81 upstream.

Until a new version of scapy is released there isn't much we can do apart from perhaps installing scapy from the master branch.

Regarding **PCAP collection shouldn't happen**. Are you sure you don't have it enabled in your ooniprobe.conf?

Regarding the Tor test timeout maybe we can bump it up to 300 seconds?

**Comment by anadahz** [comment]
Awesome it seems that everything was indeed OK, pcap set to true you were right @hellais .
Yes let's increase the timeout to at least 240 seconds.
