### ISSUE TITLE
collector-not-found while running ooniprobe with the generated deck from oonideckgen

### ISSUE THREAD

**Issue by anadahz** [TheTorProject/ooni-probe#516]
`$ tail -2 /var/log/tor/log`
```
May 30 XXX [notice] Tor has successfully opened a circuit. Looks like client functionality is working.
May 30 XXX [notice] Bootstrapped 100%: Done
```

`ooniprobe.conf`
```
# This is the configuration file for OONIProbe
# This file follows the YAML markup format: http://yaml.org/spec/1.2/spec.html
# Keep in mind that indentation matters.

basic:
    # Where OONIProbe should be writing it's log file
    logfile: /home/user/.ooni/ooniprobe.log
privacy:
    # Should we include the IP address of the probe in the report?
    includeip: false
    # Should we include the ASN of the probe in the report?
    includeasn: true
    # Should we include the country as reported by GeoIP in the report?
    includecountry: true
    # Should we include the city as reported by GeoIP in the report?
    includecity: false
    # Should we collect a full packet capture on the client?
    includepcap: false
reports:
    # This is a prefix for each packet capture file (.pcap) per test:
    pcap: null
    collector: null
advanced:
    geoip_data_dir: /home/user/ooni-probe/ooni-env/share/GeoIP
    debug: true
    # enable if auto detection fails
    #tor_binary: /usr/sbin/tor
    #obfsproxy_binary: /usr/bin/obfsproxy 
    # For auto detection
    interface: auto
    # Of specify a specific interface
    #interface: wlan0
    # If you do not specify start_tor, you will have to have Tor running and
    # explicitly set the control port and SOCKS port
    start_tor: false
    # After how many seconds we should give up on a particular measurement
    measurement_timeout: 60
    # After how many retries we should give up on a measurement
    measurement_retries: 4
    # How many measurements to perform concurrently
    measurement_concurrency: 6
    #measurement_concurrency: 10
    # After how may seconds we should give up reporting
    reporting_timeout: 80
    # After how many retries to give up on reporting
    reporting_retries: 3
    # How many reports to perform concurrently
    reporting_concurrency: 15
    oonid_api_port: 8042
tor:
    socks_port: 9050
    #control_port: 8802
    # Specify the absolute path to the Tor bridges to use for testing
    #bridges: bridges.list
    # Specify path of the tor datadirectory.
    # This should be set to something to avoid having Tor download each time
    # the descriptors and consensus data.
    #data_dir: ~/.tor/
```
`$ ooniprobe -i XXXXXX/default-user.deck`
```
WARNING: running ooniprobe involves some risk that varies greatly
         from country to country. You should be aware of this when
         running the tool. Read more about this in the manpage or README.
Log opened.
[D] Checking if backend is present
[D] Checking if backend is present
[D] Checking if backend is present
[D] Checking if dns-discovery is present
WARNING: Failed to execute tcpdump. Check it is installed and in the PATH
[D] Tor is not running. Skipping IP lookup via Tor.
Looking up your IP address via torproject
Found your IP via a GeoIP service
Fetching required net test inputs...
[D] Fetching and verifying inputs
[D] Fetching and verifying inputs
[D] Fetching and verifying inputs
Looking up collector and test helpers
[D] Got this backend error message {u'error': u'collector-not-found'}
Traceback (most recent call last):
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/ooniprobe-1.5.0-py2.7.egg/ooni/backend_client.py", line 173, in lookupTestCollector
    query={'net-tests': net_tests})
OONIBError
[!] Could not start the director
[!] Could not find a valid collector.
Try with a different bouncer, specify a collector with -c or disable reporting to a collector with -n.
Traceback (most recent call last):
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 434, in errback
    self._startRunCallbacks(fail)
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 501, in _startRunCallbacks
    self._runCallbacks()
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1184, in gotResult
    _inlineCallbacks(r, g, deferred)
--- <exception caught here> ---
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/ooniprobe-1.5.0-py2.7.egg/ooni/deck.py", line 169, in setup
    yield self.lookupCollectorAndTestHelpers()
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/ooniprobe-1.5.0-py2.7.egg/ooni/deck.py", line 310, in lookupCollectorAndTestHelpers
    response = yield oonibclient.lookupTestCollector(required_nettests)
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/ooniprobe-1.5.0-py2.7.egg/ooni/backend_client.py", line 176, in lookupTestCollector
    raise e.CouldNotFindTestCollector
ooni.errors.CouldNotFindTestCollector:
Main loop terminated.
```

**Comment by hellais** [comment]
Yes this is because we haven't yet updated the ooni-backend collector and bouncer, so it can't find the test helper address for the web_connectivity test helper.

**Comment by anadahz** [comment]
I think it makes sense in the future to tag releases to resolve other dependencies before making a release.

Leaving this ticket open in case someone encounters the same issue until we update the ooni-backend collector and bouncer.

**Comment by hellais** [comment]
I think this can be closed now since the newest version of the backend is deployed.

**Comment by BluflameSec** [comment]
I am actully getting this same issue installing on ubuntu 14.04 via apt-get. 

`WARNING: running ooniprobe involves some risk that varies greatly
         from country to country. You should be aware of this when
         running the tool. Read more about this in the manpage or README.
Log opened.
Starting Tor...
Spawning tor process with DataDirectory /tmp/tortmpC6QdHX
5%: Connecting to directory server
10%: Finishing handshake with directory server
15%: Establishing an encrypted directory connection
20%: Asking for networkstatus consensus
25%: Loading networkstatus consensus
40%: Loading authority key certs
45%: Asking for relay descriptors
50%: Loading relay descriptors
51%: Loading relay descriptors
52%: Loading relay descriptors
54%: Loading relay descriptors
57%: Loading relay descriptors
60%: Loading relay descriptors
64%: Loading relay descriptors
69%: Loading relay descriptors
73%: Loading relay descriptors
80%: Connecting to the Tor network
90%: Establishing a Tor circuit
100%: Done
Successfully bootstrapped Tor
Found your IP via Tor
Fetching required net test inputs...
Looking up collector and test helpers
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/ooni/backend_client.py", line 173, in lookupTestCollector
    query={'net-tests': net_tests})
  File "/usr/lib/python2.7/dist-packages/ooni/backend_client.py", line 156, in queryBackend
    return self._request(method, urn, genReceiver, bodyProducer, retries)
  File "/usr/lib/python2.7/dist-packages/ooni/backend_client.py", line 97, in _request
    config.tor.socks_port))
  File "/usr/lib/python2.7/dist-packages/ooni/utils/socks.py", line 23, in __init__
    self._wrappedAgent._pool = pool
AttributeError: 'TrueHeadersSOCKS5Agent' object has no attribute '_wrappedAgent'
[!] Could not start the director
[!] Could not find a valid collector.
Try with a different bouncer, specify a collector with -c or disable reporting to a collector with -n.
Main loop terminated.
`

**Comment by hellais** [comment]
@BluflameSec what version of ooniprobe are you using? Have you made any changes to the configuration?

**Comment by BluflameSec** [comment]
@hellais 

1.5.1 and no changes to the .conf was made. Sould I attach my conf file?

**Comment by hellais** [comment]
@BluflameSec upon better inspection of the output it seems like an issue with the twisted version.

Can you paste the output of:

```
python -c 'import twisted;print twisted.__version__'
```

**Comment by BluflameSec** [comment]
@hellais Says version 16.3.0 for twisted.

**Comment by hellais** [comment]
For future reference this issue was resolved on IRC and it had to do with having installed an older version of txsocksx that didn't support twisted. This in general should never happen as the twisted version (13.x) in the ubuntu repo is compatabile with the txsocksx version there (1.13.x), though this issue can arrise if the user has manually installed a more recent version of twisted, but didn't update txsocksx as well.
