### ISSUE TITLE
ooniprobe 1.5.1-1 (debian package) multiple Error in writing report entry

### ISSUE THREAD

**Issue by anadahz** [TheTorProject/ooni-probe#541]
Debian stretch
ooniprobe 1.5.1-1

-
I see a number of errors popping out while running a default generated deck:

```
[...]

[!] Error in writing report entry
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/ooni/reporter.py", line 267, in writeReportEntry
    entry_content)
OONIBError
[!] Error in writing report entry
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/ooni/reporter.py", line 267, in writeReportEntry
    entry_content)
OONIBError
* performing control request with backend
[!] Error in writing report entry
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/ooni/reporter.py", line 267, in writeReportEntry
    entry_content)
OONIBError
Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 317, in addCallback
    callbackKeywords=kw)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 306, in addCallbacks
    self._runCallbacks()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/ooni/reporter.py", line 380, in execute
    d = defer.maybeDeferred(f, *arg, **kw)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/ooni/reporter.py", line 449, in _incomplete
    raise errors.ReportNotCreated()
ooni.errors.ReportNotCreated:

[!] Error in writing report entry
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/ooni/reporter.py", line 267, in writeReportEntry
    entry_content)
OONIBError
[!] Error in writing report entry
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/ooni/reporter.py", line 267, in writeReportEntry
    entry_content)
OONIBError
[!] Error in writing report entry
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/ooni/reporter.py", line 267, in writeReportEntry
    entry_content)

[...]
```

**Comment by irl** [comment]
I have absolutely no idea what's happened here. Is this a problem with communicating with a backend or writing reports to the local filesystem?

**Comment by hellais** [comment]
From the look of it this appears to be an issue with writing report entries that have not been created.

Was this deck perhaps started during the process of updating the collector? If so it is possible that it lost the created report ID.

Do you have some timestamps for this?

**Comment by anadahz** [comment]
@hellais I don't have exact timestamps it was ~ 5 days ago.

**Comment by hellais** [comment]
I've looked a bit into this and I do see this sort of behaviour happening in some circumstances.

In the time range you mention I see this happening:

```
oonibackend.log.146:2016-06-14T10:29:41+0000 [HTTPConnection,856169,127.0.0.1] [http] 404 POST /report/20160614T054009Z_AS3320_2qrLVJIB4T3g9ExCi1VooKCMO5TggeTsvlRTQ9Y4M5DvFYQCv6 (127.0.0.1) 1506.89ms
oonibackend.log.154:2016-06-14T05:40:11+0000 [HTTPConnection,832548,127.0.0.1] [http] 200 POST /report/20160614T054009Z_AS3320_2qrLVJIB4T3g9ExCi1VooKCMO5TggeTsvlRTQ9Y4M5DvFYQCv6 (127.0.0.1) 460.35ms
```

Basically the original report is created and written around 5:40 and around that time there are many writes to the report. It then stops writing for some hours and resumes 5 hours later at around 10:40, by this time the report has become stale and is therefore automatically closed so future writes fail.

I am not sure why this happened, but one possible reason is that you were offline for some hours (or your computer was put into sleep while ooniprobe was running) and then when it came back from sleep or network connectivity came back it continued running that test and hence could not write to that report anymore.

Does this explanation seem plausible?

**Comment by anadahz** [comment]
This system is a 24/7 VM on AS34702 and I see highly unlikely the that this system has been offline since there were no signs of no network/Tor connectivity.

**Comment by hellais** [comment]
The report log has been significantly changed in 2.0.0, so this issue is probably no longer relevant. If you run into similar issues with 2.0.0 please file a new issue and reference this one.
