### ISSUE TITLE
oonireport fails to upload older reports KeyError: 'test_start_time'

### ISSUE THREAD

**Issue by anadahz** [TheTorProject/ooni-probe#554]
It seems that oonireport doesn't like older reports.

`$ oonireport -d -f ~/.ooni/ooniprobe-no-start-tor.conf upload report-XXX.yamloo`

```
Attempting to upload report-XXX.yamloo
Creating report for report-XXX.yamloo with {'front': '', 'type': 'onion', 'address': 'http://ihiderha53f36lsd.onion'}
Creating report with OONIB Reporter. Please be patient.
This may take up to 1-2 minutes...
[!] Failed to connect to reporter backend
Traceback (most recent call last):
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/ooniprobe-1.5.2.dev1-py2.7.egg/ooni/reporter.py", line 283, in createReport
    self.testDetails
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/ooniprobe-1.5.2.dev1-py2.7.egg/ooni/backend_client.py", line 321, in createReport
    'test_start_time': test_details['test_start_time'],
KeyError: 'test_start_time'
Traceback (most recent call last):
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1184, in gotResult
    _inlineCallbacks(r, g, deferred)
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    result = g.send(result)
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/ooniprobe-1.5.2.dev1-py2.7.egg/ooni/report/tool.py", line 70, in upload
    report_id = yield oonib_reporter.createReport()
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1274, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    result = g.send(result)
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/ooniprobe-1.5.2.dev1-py2.7.egg/ooni/reporter.py", line 302, in createReport
    raise errors.OONIBReportCreationError
ooni.errors.OONIBReportCreationError: 
[!] Failed to run oonireport
```

The report contains the key `start_time`: 

```
###########################################
# OONI Probe Report for http_requests (0.2.4)
# Wed Jun  4 21:29:43 2014
###########################################

---
annotations: null
input_hashes: [9f390ebfbd2da60f2f5712b6f8194db6a469a49d6f5009e6a995f64e3e716d15]
options: [-f, XXX.txt]
probe_city: null
probe_ip: 127.0.0.1
software_name: ooniprobe
software_version: 1.0.2
start_time: 1401910183.247916
test_name: http_requests
test_version: 0.2.4
```

**Comment by hellais** [comment]
I am a bit unsure if we should maintain support for uploading such old versions of reports.

Given the fact that the reports have changed so much there are many ways in which this can go wrong.

I think the best way to handle this situation would be to disallow ooni-report from uploading reports that are older than a specific version.

**Comment by anadahz** [comment]
Considering that there are a number of reports from, how does pipeline deals with those?

**Comment by hellais** [comment]
There is a normalisation procedure inside of the pipeline that deals with converting reports from an older format to a newer format. However doing it as part of the client software more prone to error.

Also I think at one point we will stop supporting YAML altogether and we should have in place already something to consider report older than a certain period no longer submittable with newer clients.

**Comment by anadahz** [comment]
In my case these reports are showing ISP block pages for some websites.if we are not to support uploading these reports by oonireport we should fix another another to upload them (somewhere?) and list them in some way.

**Comment by willscott** [comment]
Can you transform your old reports locally to include a `test_start_time` duplicating the current `start_time` key?

I don't think we should spend a huge amount of work in the repo to support generating reports off-line and then submitting them significantly later. If there's something interesting in them, we can do one-off schema migrations, since this should never be a huge volume.

**Comment by hellais** [comment]
Can we close this as wontfix? We don't want to have backward compatibility in oonireport upload.
