### ISSUE TITLE
Failure to run ooniprobe test deck without submiting reports to collector

### ISSUE THREAD

**Issue by anadahz** [TheTorProject/ooni-probe#569]
`ooniprobe version: 1.6.0`

`$ ooniprobe -v -n -i /home/user/ooni-probe/deck-XX/default-user.deck`
```
WARNING: running ooniprobe involves some risk that varies greatly
         from country to country. You should be aware of this when
         running the tool. Read more about this in the manpage or README.
Log opened.
Not reporting using a collector
[D] Checking if backend is present
[D] Checking if backend is present
[D] Checking if backend is present
[D] Checking if dns-discovery is present
WARNING: Failed to execute tcpdump. Check it is installed and in the PATH
[D] Tor is not running. Skipping IP lookup via Tor.
Looking up your IP address via torproject
Found your IP via a GeoIP service
Fetching required net test inputs...
[D] Fetching and verifying inputs
[D] Fetching and verifying inputs
[D] Fetching and verifying inputs
Looking up collector and test helpers with http://nkvphnp3p6agi5qq.onion
Unhandled Error
Traceback (most recent call last):
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/home/user/ooni-probe/ooni-env/lib/python2.7/site-packages/ooniprobe-1.6.0-py2.7.egg/EGG-INFO/scripts/ooniprobe", line 23, in <module>
    reactor.run()
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1194, in run
    self.mainLoop()
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1203, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/twisted/internet/base.py", line 825, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 419, in resolveAddress
    self._setRealAddress(self.addr)
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 434, in _setRealAddress
    self.doConnect()
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 563, in doConnect
    connectResult = self.socket.connect_ex(self.realAddress)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
exceptions.TypeError: an integer is required
```

**Comment by hellais** [comment]
Can you show me your configuration file?

I suspect you have set `start_tor: false` and you haven't configured an appropriate tor socks port in your configuration file.

**Comment by anadahz** [comment]
Contents of `ooniprobe.conf`:
```
# This is the configuration file for OONIProbe
# This file follows the YAML markup format: http://yaml.org/spec/1.2/spec.html
# Keep in mind that indentation matters.

basic:
    # Where OONIProbe should be writing it's log file
    logfile: /home/user/.ooni/ooniprobe.log
privacy:
    # Should we include the IP address of the probe in the report?
    includeip: false
    # Should we include the ASN of the probe in the report?
    includeasn: true
    # Should we include the country as reported by GeoIP in the report?
    includecountry: true
    # Should we collect a full packet capture on the client?
    includepcap: false
reports:
    # Should we place a unique ID inside of every report
    unique_id: true
    # This is a prefix for each packet capture file (.pcap) per test:
    pcap: null
    collector: null
advanced:
    debug: false
    # enable if auto detection fails
    #tor_binary: /usr/sbin/tor
    #obfsproxy_binary: /usr/bin/obfsproxy 
    # For auto detection
    interface: auto
    # Of specify a specific interface
    #interface: wlan0
    # If you do not specify start_tor, you will have to have Tor running and
    # explicitly set the control port and SOCKS port
    start_tor: true
    # After how many seconds we should give up on a particular measurement
    measurement_timeout: 60
    # After how many retries we should give up on a measurement
    measurement_retries: 2
    # How many measurements to perform concurrently
    measurement_concurrency: 10
    # After how may seconds we should give up reporting
    reporting_timeout: 80
    # After how many retries to give up on reporting
    reporting_retries: 3
    # How many reports to perform concurrently
    reporting_concurrency: 15
    oonid_api_port: 8042
    report_log_file: null
    inputs_dir: null
    decks_dir: null
    # If we should support communicating to plaintext backends (via HTTP)
    insecure_backend: false
    # The preferred backend type, can be one of onion, https or cloudfront
    preferred_backend: onion
tor:
    #socks_port: 8801
    #control_port: 8802
    # Specify the absolute path to the Tor bridges to use for testing
    #bridges: bridges.list
    # Specify path of the tor datadirectory.
    collector: null
advanced:
    debug: false
    # enable if auto detection fails
    #tor_binary: /usr/sbin/tor
    #obfsproxy_binary: /usr/bin/obfsproxy 
    # For auto detection
    interface: auto
    # Of specify a specific interface
    #interface: wlan0
    # If you do not specify start_tor, you will have to have Tor running and
    # explicitly set the control port and SOCKS port
    start_tor: true
    # After how many seconds we should give up on a particular measurement
    measurement_timeout: 60
    # After how many retries we should give up on a measurement
    measurement_retries: 2
    # How many measurements to perform concurrently
    measurement_concurrency: 10
    # After how may seconds we should give up reporting
    reporting_timeout: 80
    # After how many retries to give up on reporting
    reporting_retries: 3
    # How many reports to perform concurrently
    reporting_concurrency: 15
    oonid_api_port: 8042
    report_log_file: null
    inputs_dir: null
    decks_dir: null
    # If we should support communicating to plaintext backends (via HTTP)
    insecure_backend: false
    # The preferred backend type, can be one of onion, https or cloudfront
    preferred_backend: onion
tor:
    #socks_port: 8801
    #control_port: 8802
    # Specify the absolute path to the Tor bridges to use for testing
    #bridges: bridges.list
    # Specify path of the tor datadirectory.
    # This should be set to something to avoid having Tor download each time
    # the descriptors and consensus data.
    #data_dir: ~/.tor/
    #
    # This is the timeout after which we consider to to not have
    # bootstrapped properly.
    timeout: 200
    torrc:
        #HTTPProxy: host:port
        #HTTPProxyAuthenticator: user:password
        #HTTPSProxy: host:port
        #HTTPSProxyAuthenticator: user:password
        #UseBridges: 1
        #Bridge:
        #- "meek_lite 0.0.2.0:1 url=https://meek-reflect.appspot.com/ front=www.google.com"
        #- "meek_lite 0.0.2.0:2 url=https://d2zfqthxsdq309.cloudfront.net/ front=a0.awsstatic.com"
        #- "meek_lite 0.0.2.0:3 url=https://az786092.vo.msecnd.net/ front=ajax.aspnetcdn.com"
        #ClientTransportPlugin: "meek_lite exec /usr/bin/obfs4proxy"
```

**Comment by hellais** [comment]
Yes I can confirm this is a bug and I can reproduce. It seems to be happening when reporting to a collector is disabled.

I will push a hotfix for this to master.
