### ISSUE TITLE
Investigate "dirty reactor" problems in unittests

### ISSUE THREAD

**Issue by hellais** [TheTorProject/ooni-probe#572]
Some of the unittests will fail due to a "dirty reactor" from time to time.

Since these errors are due to timing, it's hard to reproduce them stably, but some of the tracebacks from the failures give an idea of where to look to fix this behaviour:

```
[ERROR]
Traceback (most recent call last):
Failure: twisted.internet.defer.TimeoutError: <ooni.tests.test_oonicli.TestRunDirector testMethod=test_http_requests> (test_http_requests) still running at 220.0 secs
ooni.tests.test_oonicli.TestRunDirector.test_http_requests
===============================================================================
[ERROR]
Traceback (most recent call last):
Failure: twisted.trial.util.DirtyReactorAggregateError: Reactor was unclean.
DelayedCalls: (set twisted.internet.base.DelayedCall.debug = True to debug)
<DelayedCall 0x7f26717ab5f0 [19.9905939102s] called=0 cancelled=0 Measurement._timedOut()
traceback at creation: 
  File "/home/travis/virtualenv/python2.7.9/bin/coverage", line 9, in <module>
    load_entry_point('coverage==4.1', 'console_scripts', 'coverage')()
      File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/coverage/cmdline.py", line 746, in main
    status = CoverageScript().command_line(argv)
      File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/coverage/cmdline.py", line 482, in command_line
    return self.do_run(options, args)
      File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/coverage/cmdline.py", line 625, in do_run
    self.run_python_file(filename, args)
      File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/coverage/execfile.py", line 177, in run_python_file
    exec(code, main_mod.__dict__)
      File "/home/travis/virtualenv/python2.7.9/bin/trial", line 18, in <module>
    run()
      File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/twisted/scripts/trial.py", line 615, in run
    test_result = trialRunner.run(suite)
      File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/twisted/trial/runner.py", line 729, in run
    return self._runWithoutDecoration(test, self._forceGarbageCollection)
      File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/twisted/trial/runner.py", line 756, in _runWithoutDecoration
    run()
      File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/twisted/trial/runner.py", line 751, in <lambda>
    run = lambda: suite.run(result)
      File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/twisted/trial/runner.py", line 219, in run
    TestSuite.run(self, result)
      File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/twisted/trial/_asyncrunner.py", line 36, in run
    test(result)
      File "/opt/python/2.7.9/lib/python2.7/unittest/suite.py", line 70, in __call__
    return self.run(*args, **kwds)
      File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/twisted/trial/runner.py", line 178, in run
    super(LoggedSuite, self).run(result)
      File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/twisted/trial/_asyncrunner.py", line 36, in run
    test(result)
      File "/opt/python/2.7.9/lib/python2.7/unittest/suite.py", line 70, in __call__
    return self.run(*args, **kwds)
      File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/twisted/trial/runner.py", line 151, in run
    test(result)
      File "/opt/python/2.7.9/lib/python2.7/unittest/suite.py", line 70, in __call__
    return self.run(*args, **kwds)
      File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/twisted/trial/runner.py", line 151, in run
    test(result)
      File "/opt/python/2.7.9/lib/python2.7/unittest/suite.py", line 70, in __call__
    return self.run(*args, **kwds)
      File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/twisted/trial/runner.py", line 151, in run
    test(result)
      File "/opt/python/2.7.9/lib/python2.7/unittest/suite.py", line 70, in __call__
    return self.run(*args, **kwds)
      File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/twisted/trial/runner.py", line 151, in run
    test(result)
      File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/twisted/trial/_asynctest.py", line 113, in __call__
    return self.run(*args, **kwargs)
      File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/twisted/trial/_synctest.py", line 943, in run
    _collectWarnings(self._warnings.append, self._runFixturesAndTest, result)
      File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/twisted/trial/_synctest.py", line 182, in _collectWarnings
    result = f(*args, **kwargs)
      File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/twisted/trial/_asynctest.py", line 294, in _runFixturesAndTest
    self._wait(d)
      File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/twisted/trial/_asynctest.py", line 372, in _wait
    reactor.run()
      File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/twisted/internet/base.py", line 1192, in run
    self.mainLoop()
      File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/twisted/internet/base.py", line 1201, in mainLoop
    self.runUntilCurrent()
      File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/twisted/internet/base.py", line 824, in runUntilCurrent
    call.func(*call.args, **call.kw)
      File "/home/travis/build/TheTorProject/ooni-probe/ooni/tasks.py", line 76, in _timedOut
    self._running.cancel()
      File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/twisted/internet/defer.py", line 470, in cancel
    self.result.cancel()
      File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/twisted/internet/defer.py", line 467, in cancel
    self.errback(failure.Failure(CancelledError()))
      File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/twisted/internet/defer.py", line 423, in errback
    self._startRunCallbacks(fail)
      File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
    self._runCallbacks()
      File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/twisted/internet/defer.py", line 577, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
      File "/home/travis/build/TheTorProject/ooni-probe/ooni/managers.py", line 164, in _failed
    super(LinkedTaskManager, self)._failed(result, task)
      File "/home/travis/build/TheTorProject/ooni-probe/ooni/managers.py", line 51, in _failed
    self._fillSlots()
      File "/home/travis/build/TheTorProject/ooni-probe/ooni/managers.py", line 61, in _fillSlots
    d.addCallback(lambda _: self._scheduleNextTask())
      File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/twisted/internet/defer.py", line 306, in addCallback
    callbackKeywords=kw)
      File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/twisted/internet/defer.py", line 295, in addCallbacks
    self._runCallbacks()
      File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/twisted/internet/defer.py", line 577, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
      File "/home/travis/build/TheTorProject/ooni-probe/ooni/managers.py", line 61, in <lambda>
    d.addCallback(lambda _: self._scheduleNextTask())
      File "/home/travis/build/TheTorProject/ooni-probe/ooni/managers.py", line 67, in _scheduleNextTask
    self._run(task)
      File "/home/travis/build/TheTorProject/ooni-probe/ooni/managers.py", line 79, in _run
    d = task.start()
      File "/home/travis/build/TheTorProject/ooni-probe/ooni/tasks.py", line 91, in start
    self._timer = self.clock.callLater(self.timeout, self._timedOut)
>
ooni.tests.test_oonicli.TestRunDirector.test_http_requests
===============================================================================
[ERROR]
Traceback (most recent call last):
Failure: twisted.trial.util.DirtyReactorAggregateError: Reactor was unclean.
Selectables:
<<class 'twisted.internet.tcp.Client'> to ('127.0.0.1', 9050) at 7f26716e9090>
```

It seems to happen when one of the integration tests for the ooniprobe tests timeout and therefore the task timeout.

**Comment by hellais** [comment]
This has been fixed.
