### ISSUE TITLE
Traceroute test: TypeError(repr(o) + " is not JSON serializable")

### ISSUE THREAD

**Issue by anadahz** [TheTorProject/ooni-probe#577]
`ooniprobe version: 1.6.1`

`$ ooniprobe --preferred-backend=https traceroute`
```
WARNING: running ooniprobe involves some risk that varies greatly
         from country to country. You should be aware of this when
         running the tool. Read more about this in the manpage or README.
Log opened.
WARNING: Failed to execute tcpdump. Check it is installed and in the PATH
Looking up your IP address via ubuntu
Found your IP via a GeoIP service
Fetching required net test inputs...
Looking up collector and test helpers with https://bouncer.ooni.io
Setting collector and test helpers for traceroute
Creating report with OONIB Reporter. Please be patient.
This may take up to 1-2 minutes...
Running TCP traceroute towards None
This will take about 57.2 seconds
Running ICMP traceroute towards None
This will take about 57.2 seconds
Running UDP traceroute towards None
This will take about 57.2 seconds
[!] Error in writing report entry
Traceback (most recent call last):
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/ooniprobe-1.6.1-py2.7.egg/ooni/reporter.py", line 267, in writeReportEntry
    entry_content)
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/ooniprobe-1.6.1-py2.7.egg/ooni/backend_client.py", line 339, in updateReport
    query=request)
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/ooniprobe-1.6.1-py2.7.egg/ooni/backend_client.py", line 139, in queryBackend
    bodyProducer = StringProducer(json.dumps(query))
  File "/usr/lib/python2.7/json/__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <IP  id=29129 frag=0 ttl=1 proto=tcp dst=127.0.0.1 |<TCP  sport=36345 dport=0 seq=13390 flags=S |>> is not JSON serializable
```

**Comment by hellais** [comment]
It seems like the hotfix for this issue didn't make it inside of the release 1.6.1.

It's actually fixed in the latest master of ooniprobe, but isn't part of the 1.6.1 release.

As a side note, I think that our traceroute algorithm is flawed and won't really give us much actionable results. That is to say that measurements from traceroute are not going to be particularly usable and I think the best path forward for implementing it is integrating the techniques from paris traceroute.

**Comment by hellais** [comment]
This is fixed in master I am going to consider this issue closed.
