### ISSUE TITLE
when run as a normal user oonideckgen should auto create required ~/.ooni if it doesn't exist

### ISSUE THREAD

**Issue by kaerumy** [TheTorProject/ooni-probe#583]
```
$ oonideckgen 
Resources for running ooniprobe are not up to date.
Will update them now.
Downloading https://github.com/TheTorProject/ooni-probe/releases/download/v1.6.0/ooni-resources.tar.gz to /home/xxxxx/.ooni
Failed to download resources!
[!] Failed to run oonideckgen
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 434, in errback
    self._startRunCallbacks(fail)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 501, in _startRunCallbacks
    self._runCallbacks()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1184, in gotResult
    _inlineCallbacks(r, g, deferred)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/lib/python2.7/dist-packages/ooni/deckgen/cli.py", line 148, in run
    yield download_resources()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    result = g.send(result)
  File "/usr/lib/python2.7/dist-packages/ooni/resources/update.py", line 54, in download_resources
    raise exc
exceptions.OSError: [Errno 2] No such file or directory
```

**Comment by hellais** [comment]
oonideckgen is deprecated since 2.0.0. Closing
