### ISSUE TITLE
traceroute test: inp, out, err = select(inmask,[],[], remaintime), select.error: (4, 'Interrupted system call')

### ISSUE THREAD

**Issue by anadahz** [TheTorProject/ooni-probe#585]
`$ pip freeze`

```
GeoIP==1.3.2
Parsley==1.3
PyYAML==3.11
Twisted==16.3.0
argparse==1.2.1
attrs==15.2.0
certifi==2016.8.2
cffi==1.6.0
characteristic==14.3.0
cryptography==1.3.1
enum34==1.1.4
fte==0.1.0
fteproxy==0.2.19
idna==2.1
ipaddr==2.1.11
ipaddress==1.0.16
obfsproxy==0.2.13
ooniprobe==1.6.2.dev0
pyOpenSSL==16.0.0
pyasn1==0.1.9
pyasn1-modules==0.0.8
pycparser==2.14
pycrypto==2.6.1
pydumbnet==1.12.1
pypcap==1.1.5
pyptlib==0.0.6
scapy==2.3.2.dev0
service-identity==16.0.0
six==1.10.0
txsocksx==1.15.0.2
txtorcon==0.15.0
wsgiref==0.1.2
zope.interface==4.2.0
```

`oniprobe version: 1.6.2.dev0`

`$ ooniprobe --preferred-backend=https traceroute`

```
WARNING: running ooniprobe involves some risk that varies greatly
         from country to country. You should be aware of this when
         running the tool. Read more about this in the manpage or README.
Log opened.
Looking up your IP address via ubuntu
Found your IP via a GeoIP service
Fetching required net test inputs...
Looking up collector and test helpers with https://bouncer.ooni.io
Setting collector and test helpers for traceroute
Creating report with OONIB Reporter. Please be patient.
This may take up to 1-2 minutes...
Running TCP traceroute towards 213.138.109.232
This will take about 57.2 seconds
Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    result = g.send(result)
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/ooniprobe-1.6.2.dev0-py2.7.egg/ooni/nettests/manipulation/traceroute.py", line 63, in run_traceroute
    yield traceroute(self.localOptions['backend'])
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/ooniprobe-1.6.2.dev0-py2.7.egg/ooni/utils/txscapy.py", line 380, in TCPTraceroute
    seq=RandShort()))
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1274, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    result = g.send(result)
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/ooniprobe-1.6.2.dev0-py2.7.egg/ooni/utils/txscapy.py", line 396, in sendPackets
    self.factory.super_socket.send(packet)
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/scapy/arch/pcapdnet.py", line 575, in send
    sx = str(cls()/x)
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/scapy/packet.py", line 277, in __str__
    return self.build()
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/scapy/packet.py", line 354, in build
    p = self.do_build()
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/scapy/packet.py", line 341, in do_build
    pkt = self.self_build()
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/scapy/packet.py", line 332, in self_build
    p = f.addfield(self, p, val)
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/scapy/fields.py", line 72, in addfield
    return s+struct.pack(self.fmt, self.i2m(pkt,val))
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/scapy/layers/l2.py", line 101, in i2m
    return MACField.i2m(self, pkt, self.i2h(pkt, x))
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/scapy/layers/l2.py", line 93, in i2h
    x = conf.neighbor.resolve(pkt,pkt.payload)
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/scapy/layers/l2.py", line 41, in resolve
    return self.resolvers[k](l2inst,l3inst)
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/scapy/layers/inet.py", line 778, in <lambda>
    conf.neighbor.register_l3(Ether, IP, lambda l2,l3: getmacbyip(l3.dst))
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/scapy/layers/l2.py", line 76, in getmacbyip
    nofilter=1)
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/scapy/sendrecv.py", line 392, in srp1
    a,b=srp(*args,**kargs)
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/scapy/sendrecv.py", line 375, in srp
    a,b=sndrcv(s ,x,*args,**kargs)
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/scapy/sendrecv.py", line 134, in sndrcv
    inp, out, err = select(inmask,[],[], remaintime)
select.error: (4, 'Interrupted system call')
```

**Comment by hellais** [comment]
Is this still an issue with the version of scapy that includes my fixes?

I believe this can be closed now.

**Comment by anadahz** [comment]
Indeed closing.
