### ISSUE TITLE
Twisted (16.5.0rc1): cannot start ooniprobe-agent

### ISSUE THREAD

**Issue by anadahz** [TheTorProject/ooni-probe#638]
Twisted version 16.5.0rc1 has been pulled from the pip install line:
 https://github.com/TheTorProject/lepidopter/blob/master/lepidopter-fh/setup-ooniprobe.sh#L22
`$ pip list`
```
argparse (1.2.1)
attrs (16.2.0)
certifi (2016.9.26)
cffi (1.8.3)
chardet (2.3.0)
colorama (0.3.2)
constantly (15.1.0)
cryptography (1.5.2)
enum34 (1.1.6)
fte (0.1.3)
fteproxy (0.2.19)
GeoIP (1.3.2)
html5lib (0.999)
idna (2.1)
incremental (16.10.0)
ipaddr (2.1.11)
ipaddress (1.0.17)
klein (15.3.1)
obfsproxy (0.2.13)
ooniprobe (2.0.0)
Parsley (1.3)
pip (1.5.6)
ply (3.4)
pyasn1 (0.1.9)
pyasn1-modules (0.0.8)
pycparser (2.10)
pycrypto (2.6.1)
pydumbnet (1.12.1)
pyOpenSSL (16.2.0)
pypcap (1.1.5)
pyptlib (0.0.6)
PyYAML (3.12)
requests (2.4.3)
scapy (2.3.2)
service-identity (16.0.0)
setuptools (28.5.0)
six (1.8.0)
Twisted (16.5.0rc1)
txsocksx (1.15.0.2)
txtorcon (0.17.0)
urllib3 (1.9.1)
Werkzeug (0.11.11)
wheel (0.24.0)
wsgiref (0.1.2)
zope.interface (4.3.2)
```
`journactl` excerpt:
```
Oct 16 17:49:30 lepidopter systemd[1]: Starting ooniprobe.service, network interference detection tool...
Oct 16 17:49:30 lepidopter systemd[1]: Started Update UTMP about System Runlevel Changes.
Oct 16 17:49:44 lepidopter ooniprobe-agent[615]: Traceback (most recent call last):
Oct 16 17:49:44 lepidopter ooniprobe-agent[615]: File "/usr/local/bin/ooniprobe-agent", line 9, in <module>
Oct 16 17:49:44 lepidopter ooniprobe-agent[615]: load_entry_point('ooniprobe==2.0.0', 'console_scripts', 'ooniprobe-agent')()
Oct 16 17:49:44 lepidopter ooniprobe-agent[615]: File "build/bdist.linux-armv7l/egg/pkg_resources/__init__.py", line 567, in load_entry_point
Oct 16 17:49:44 lepidopter ooniprobe-agent[615]: File "build/bdist.linux-armv7l/egg/pkg_resources/__init__.py", line 2604, in load_entry_point
Oct 16 17:49:44 lepidopter ooniprobe-agent[615]: File "build/bdist.linux-armv7l/egg/pkg_resources/__init__.py", line 2264, in load
Oct 16 17:49:44 lepidopter ooniprobe-agent[615]: File "build/bdist.linux-armv7l/egg/pkg_resources/__init__.py", line 2270, in resolve
Oct 16 17:49:44 lepidopter ooniprobe-agent[615]: File "/usr/local/lib/python2.7/dist-packages/ooniprobe-2.0.0-py2.7.egg/ooni/scripts/ooniprobe_agent.py", line 14, in <module>
Oct 16 17:49:44 lepidopter ooniprobe-agent[615]: from ooni.agent.agent import AgentService
Oct 16 17:49:44 lepidopter ooniprobe-agent[615]: File "/usr/local/lib/python2.7/dist-packages/ooniprobe-2.0.0-py2.7.egg/ooni/agent/agent.py", line 2, in <module>
Oct 16 17:49:44 lepidopter ooniprobe-agent[615]: from ooni.director import Director
Oct 16 17:49:44 lepidopter ooniprobe-agent[615]: File "/usr/local/lib/python2.7/dist-packages/ooniprobe-2.0.0-py2.7.egg/ooni/director.py", line 12, in <module>
Oct 16 17:49:44 lepidopter ooniprobe-agent[615]: from ooni.deck.store import input_store, deck_store
Oct 16 17:49:44 lepidopter ooniprobe-agent[615]: File "/usr/local/lib/python2.7/dist-packages/ooniprobe-2.0.0-py2.7.egg/ooni/deck/__init__.py", line 1, in <module>
Oct 16 17:49:44 lepidopter ooniprobe-agent[615]: from .deck import NGDeck
Oct 16 17:49:44 lepidopter ooniprobe-agent[615]: File "/usr/local/lib/python2.7/dist-packages/ooniprobe-2.0.0-py2.7.egg/ooni/deck/deck.py", line 12, in <module>
Oct 16 17:49:44 lepidopter ooniprobe-agent[615]: from ooni.backend_client import BouncerClient, CollectorClient
Oct 16 17:49:44 lepidopter ooniprobe-agent[615]: File "/usr/local/lib/python2.7/dist-packages/ooniprobe-2.0.0-py2.7.egg/ooni/backend_client.py", line 19, in <module>
Oct 16 17:49:44 lepidopter ooniprobe-agent[615]: from ooni.utils.socks import TrueHeadersSOCKS5Agent
Oct 16 17:49:44 lepidopter ooniprobe-agent[615]: File "/usr/local/lib/python2.7/dist-packages/ooniprobe-2.0.0-py2.7.egg/ooni/utils/socks.py", line 8, in <module>
Oct 16 17:49:44 lepidopter ooniprobe-agent[615]: from txsocksx.http import SOCKS5Agent
Oct 16 17:49:44 lepidopter ooniprobe-agent[615]: File "build/bdist.linux-armv7l/egg/txsocksx/http.py", line 24, in <module>
Oct 16 17:49:44 lepidopter ooniprobe-agent[615]: File "/usr/local/lib/python2.7/dist-packages/incremental-16.10.0-py2.7.egg/incremental/__init__.py", line 341, in __cmp__
Oct 16 17:49:44 lepidopter ooniprobe-agent[615]: % (self.package, other.package))
Oct 16 17:49:44 lepidopter ooniprobe-agent[615]: incremental.IncomparableVersions: 'Twisted' != 'twisted'
Oct 16 17:49:44 lepidopter systemd[1]: ooniprobe.service: control process exited, code=exited status=1
Oct 16 17:49:44 lepidopter systemd[1]: Failed to start ooniprobe.service, network interference detection tool.
```

**Comment by hellais** [comment]
While I think we may be able to implement some workaround specific for ooniprobe (probably by pinning the version of twisted we use to something that works).

The bug is actually something that should live in either txsocksx or Twisted.

**Comment by hellais** [comment]
filed an issue on twisted: https://twistedmatrix.com/trac/ticket/8863

**Comment by hellais** [comment]
This has been fixed in upstream see:
https://twistedmatrix.com/trac/ticket/8863#comment:6
https://github.com/twisted/twisted/commit/901f42932739070b1189829751c70d5f27ae1b09
