### ISSUE TITLE
Ubuntu install : bug in oonideckgen

### ISSUE THREAD

**Issue by Te-k** [TheTorProject/ooni-probe#648]
Hi,
I installed ooniprobe from the Ubuntu 16.04 repository and had the following bug when running oonideckgen : 
```
$ oonideckgen 
Resources for running ooniprobe are not up to date.
Will update them now.
Downloading https://github.com/TheTorProject/ooni-probe/releases/download/v1.6.0/ooni-resources.tar.gz to /home/user/.ooni
Failed to download resources!
[!] Failed to run oonideckgen
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 434, in errback
    self._startRunCallbacks(fail)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 501, in _startRunCallbacks
    self._runCallbacks()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1184, in gotResult
    _inlineCallbacks(r, g, deferred)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/lib/python2.7/dist-packages/ooni/deckgen/cli.py", line 148, in run
    yield download_resources()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    result = g.send(result)
  File "/usr/lib/python2.7/dist-packages/ooni/resources/update.py", line 54, in download_resources
    raise exc
exceptions.OSError: [Errno 2] No such file or directory
```

The problem was resolved by creating manually the .ooni directory in the home folder. It would be interesting to create automatically this directory in the deckgen script.

Ubuntu 16.04.1 LTS with oonideckgen version: 0.2.0

**Comment by anadahz** [comment]
@Te-k Thanks for reporting back.
We have very recently released ooniprobe version 2.0.0 and will highly recommend you to use the newest version.
We have no Ubuntu packages but you can install it via pip, install instructions (not yet merged): https://github.com/TheTorProject/ooni-probe/pull/649.

**Comment by Te-k** [comment]
Hi  @anadahz,
Thanks for your answer, I solved the problem by creating the .ooni manually so it worked and I could run my tests. 
I have tested the new install, and I did not have any problem with it (minor suggestion is that the first time you run ooni, you have to answer some questions but the tests are not launched, you have to launch ooni again which is a bit counter-intuitive)

**Comment by anadahz** [comment]
> I have tested the new install, and I did not have any problem with it (minor suggestion is that the first time you run ooni, you have to answer some questions but the tests are not launched, you have to launch ooni again which is a bit counter-intuitive)

This shouldn't happen, sometimes the tests require some time to show up in measurements.

@Te-k could you please check if this is not the case and report as a new issue to investigate further?

**Comment by Te-k** [comment]
Done with #650

I close this issue as solved in the new version
