### ISSUE TITLE
Syntax bug in oonideckgen --version

### ISSUE THREAD

**Issue by Te-k** [TheTorProject/ooni-probe#651]
Minor bug : 
```bash
$ python oonideckgen.py --version
main function encountered error
Traceback (most recent call last):
  File "oonideckgen.py", line 131, in <module>
    run()
[SNIP]
  File "oonideckgen.py", line 33, in opt_version
    print("oonideckgen version: " % __version__)
exceptions.TypeError: not all arguments converted during string formatting
```

In oonideckgen.py, line 33
```python
print("oonideckgen version: " % __version__)
```
should be
```python
 print("oonideckgen version: %s" % __version__)
```

**Comment by hellais** [comment]
Good call.

This should be fixed, though note that oonideckgen is deprecated since 2.0.0.
