### ISSUE TITLE
Fail to use cloudfront as the preferred backend type.  

### ISSUE THREAD

**Issue by anadahz** [TheTorProject/ooni-probe#795]
### Description

Cannot use cloudfront collector on fresh install.  

### Steps to Reproduce

1. Install ooniprobe in a virtualenv
2. Bootstrap ooniprobe and set cloudfront as the default collector  
3. Run web connectivity test

<details><summary>Backtrace of the error</summary>

`oniprobe web_connectivity --url https://www.torproject.org`
```
Looking up your IP address via ubuntu
Found your IP via a GeoIP service
Looking up collector and test helpers with https://a0.awsstatic.com
[!] Could not start the director
[!] An unhandled exception occurred while starting the director!
Unhandled Error
Traceback (most recent call last):
--- <exception caught here> ---
  File "/home/user/ooni-probe/venv/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/user/ooni-probe/venv/local/lib/python2.7/site-packages/ooniprobe-2.3.0-py2.7.egg/ooni/ui/cli.py", line 129, in director_startup_handled_failures
    SystemExit)
  File "/home/user/ooni-probe/venv/local/lib/python2.7/site-packages/twisted/python/failure.py", line 441, in trap
    raise self
  File "/home/user/ooni-probe/venv/local/lib/python2.7/site-packages/ooniprobe-2.3.0-py2.7.egg/ooni/ui/cli.py", line 380, in post_director_start
    yield deck.run(director, from_schedule=False)
  File "/home/user/ooni-probe/venv/local/lib/python2.7/site-packages/ooniprobe-2.3.0-py2.7.egg/ooni/deck/deck.py", line 292, in run
    yield self.query_bouncer()
  File "/home/user/ooni-probe/venv/local/lib/python2.7/site-packages/ooniprobe-2.3.0-py2.7.egg/ooni/deck/deck.py", line 207, in query_bouncer
    self.no_collector
  File "/home/user/ooni-probe/venv/local/lib/python2.7/site-packages/ooniprobe-2.3.0-py2.7.egg/ooni/deck/backend.py", line 153, in lookup_collector_and_test_helpers
    response['net-tests'], preferred_backend)
  File "/home/user/ooni-probe/venv/local/lib/python2.7/site-packages/ooniprobe-2.3.0-py2.7.egg/ooni/deck/backend.py", line 105, in get_reachable_test_helpers_and_collectors
    primary_address, alternate_addresses, preferred_backend)
  File "/home/user/ooni-probe/venv/local/lib/python2.7/site-packages/ooniprobe-2.3.0-py2.7.egg/ooni/deck/backend.py", line 88, in get_reachable_collector
    reachable = yield collector.isReachable()
  File "/home/user/ooni-probe/venv/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/user/ooni-probe/venv/local/lib/python2.7/site-packages/ooniprobe-2.3.0-py2.7.egg/ooni/backend_client.py", line 212, in err
    failure.trap(Error)
  File "/home/user/ooni-probe/venv/local/lib/python2.7/site-packages/twisted/python/failure.py", line 441, in trap
    raise self
ooni.errors.OONIBError: 
```
</details>

**Expected behavior:** Perform the web connectivity test

**Actual behavior:**  ooniprobe fails to perform the web connectivity test

### Further information

**How did you install ooniprobe**

Installed ooniprobe in Debian 9 within a virtualenv from the current master git repository (bdd86c3c6da6bf82a713a2b34a728d2929faeaae).

<details><summary>Output of `ooniprobe -v --info`</summary>

```
Paths
-----
inputs directory: /home/user/ooni-probe/venv/var/lib/ooni/inputs
scheduler directory: /home/user/ooni-probe/venv/var/lib/ooni/scheduler
resources directory: /home/user/ooni-probe/venv/var/lib/ooni/resources
decks available directory: /home/user/ooni-probe/venv/share/ooni/decks-available
decks enabled directory: /home/user/ooni-probe/venv/var/lib/ooni/decks-enabled
measurements directory: /home/user/ooni-probe/venv/var/lib/ooni/measurements
running path: /home/user/ooni-probe/venv/var/lib/ooni
config files: /home/user/ooni-probe/venv/var/lib/ooni/ooniprobe.conf,/etc/ooniprobe.conf
ooni home: /home/user/.ooni
var_lib path: /home/user/ooni-probe/venv/var/lib/ooni
etc path: /home/user/ooni-probe/venv/etc
usr_share path: /home/user/ooni-probe/venv/share/ooni
nettest directory: /home/user/ooni-probe/venv/lib/python2.7/site-packages/ooniprobe-2.3.0-py2.7.egg/ooni/nettests
web ui directory: /home/user/ooni-probe/venv/lib/python2.7/site-packages/ooniprobe-2.3.0-py2.7.egg/ooni/ui/web/client
```
</details>

<details><summary>Output of `ooniprobe --version`</summary>

```
ooniprobe version: 2.3.0
```
</details>

**Comment by hellais** [comment]
It looks like fronting via `a0.awsstatic.com` onto our cloudfront endpoint doesn't work anymore. This is likely due to recent developments on the side of the cloud provider.

Given that this is a soon to be deprecated version of OONI Probe and given that the this provider in question doesn't support this method anymore (though we do see a bit a traffic to it, but don't want to make too big of a deal out of that), I am closing this as wontfix.
